name: david_advmobprog
description: "facebook_replication"
publish_to: "none"
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  http: ^1.5.0
  provider: ^6.1.5
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true