// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK8ihFNW7YFSCKoggLuNip-AD60YV7V0k',
    appId: '1:91097460341:web:e1ca03577bcb218b32d23c',
    messagingSenderId: '91097460341',
    projectId: 'adv-mob-9b05a',
    authDomain: 'adv-mob-9b05a.firebaseapp.com',
    storageBucket: 'adv-mob-9b05a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH5g0eoyTQK0i6YVcdNNFVzQaWoLj51ps',
    appId: '1:91097460341:android:42b7f2fe1186eeea32d23c',
    messagingSenderId: '91097460341',
    projectId: 'adv-mob-9b05a',
    storageBucket: 'adv-mob-9b05a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0rqaIxlrEXvOBvSBJUxXey9J0FhyrKgg',
    appId: '1:91097460341:ios:0e59336b0fdaf0c832d23c',
    messagingSenderId: '91097460341',
    projectId: 'adv-mob-9b05a',
    storageBucket: 'adv-mob-9b05a.firebasestorage.app',
    iosBundleId: 'com.example.lab1Advmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0rqaIxlrEXvOBvSBJUxXey9J0FhyrKgg',
    appId: '1:91097460341:ios:0e59336b0fdaf0c832d23c',
    messagingSenderId: '91097460341',
    projectId: 'adv-mob-9b05a',
    storageBucket: 'adv-mob-9b05a.firebasestorage.app',
    iosBundleId: 'com.example.lab1Advmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK8ihFNW7YFSCKoggLuNip-AD60YV7V0k',
    appId: '1:91097460341:web:1e7fdf70b1ca1acf32d23c',
    messagingSenderId: '91097460341',
    projectId: 'adv-mob-9b05a',
    authDomain: 'adv-mob-9b05a.firebaseapp.com',
    storageBucket: 'adv-mob-9b05a.firebasestorage.app',
  );

}